### PR TITLE
new lxdone image

### PR DESCRIPTION
**Pull request by jmdelafe**
Improved image for new LXDoNe release

### CODE REVIEW

**Comment by vholer** [comment]
I have fixed the new image checksums:
md5: 876699b33accf39700522252fbfde566
sha256: c44c0709f0afd6ac06b24c68c46a7a4e6ab35190f889192544c73e5729bea90f

Please, confirm these checksums are valid. After that, I'll refresh the running Marketplace. Thanks!

**Comment by jmdelafe** [comment]
These checksums are valid for lxdone-5.2-4.1.img.gz :+1:

**Comment by vholer** [comment]
OK, update appliance is now public. Thank you!

**Comment by jmdelafe** [comment]
Ok. Thanks!

**Pull request merged**
