### PR TITLE
Add Devuan Ascii image

### PR DESCRIPTION
**Pull request by AnotherKamila**
Created a Devuan Ascii image.

---
This change is [Reviewable](https://reviewable.io/reviews/opennebula/marketplace/6)

### CODE REVIEW

**Comment by vholer** [comment]
Hello Kamila,

as the Devuan is our supported target platform (https://github.com/OpenNebula/addon-context-linux#tested-platforms), we already have **Devuan 2 Beta** image under our testing. We'll provide the KVM image to the Marketplace as soon as the Devuan 2 released.

Thank you for understanding,
Vlastimil Holer

**Comment by AnotherKamila** [comment]
Hello,

OK, thanks for the info! (Wish I'd known that sooner... :D)

Kamila

**Comment by vholer** [comment]
Hello,

I'm sorry, this is our fault. We don't have good instructions about what appliances make sense to prepare and accept. Also as I see, it would be good to have our beta image builds available to the users (not via the same main Marketplace, some other way). We'll think about it.

Anyway, if you want, you can share your beta image with other users on the Forum (https://forum.opennebula.org/).

Best regards,
Vlastimil

**Comment by vholer** [comment]
We now have Devuan 2 stable in the Marketplace:
http://marketplace.opennebula.org/appliance/68b57592-2572-4135-91ac-0ece957babda

**Pull request closed without merging**
